/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: "var(--color-primary)",
        "primary-highlight": "var(--color-primary-highlight)",
        "orange-highlight": "var(--color-orange-highlight)",
        dark: "var(--color-dark)",
        charcoal: "var(--color-charcoal)",
        purple: "var(--color-purple)",
        pink: "var(--color-pink)",
        brown: "var(--color-brown)",
        carton: "var(--color-carton)",
        "sky-blue": "var(--color-sky-blue)",
        "dark-blue": "var(--color-dark-blue)",
        blue: "var(--color-blue)",
        red: "var(--color-red)",
        green: "var(--color-green)",
        yellow: "var(--color-yellow)",
        // Opacity variants
        "d-3": "var(--color-d-3)",
        "d-5": "var(--color-d-5)",
        "d-7": "var(--color-d-7)",
        "d-10": "var(--color-d-10)",
        "d-15": "var(--color-d-15)",
        "d-20": "var(--color-d-20)",
        "d-25": "var(--color-d-25)",
        "d-30": "var(--color-d-30)",
        "d-40": "var(--color-d-40)",
        "d-50": "var(--color-d-50)",
        "d-60": "var(--color-d-60)",
        "d-70": "var(--color-d-70)",
        "d-80": "var(--color-d-80)",
        "d-90": "var(--color-d-90)",
        "d-100": "var(--color-d-100)",
        "r-3": "var(--color-r-3)",
        "r-5": "var(--color-r-5)",
        "r-7": "var(--color-r-7)",
        "r-10": "var(--color-r-10)",
        "r-15": "var(--color-r-15)",
        "r-20": "var(--color-r-20)",
        "r-25": "var(--color-r-25)",
        "r-30": "var(--color-r-30)",
        "r-40": "var(--color-r-40)",
        "r-50": "var(--color-r-50)",
        "r-60": "var(--color-r-60)",
        "r-70": "var(--color-r-70)",
        "r-80": "var(--color-r-80)",
        "r-90": "var(--color-r-90)",
        "r-100": "var(--color-r-100)",
        "table-border": "var(--color-table-border)",
        "table-shade": "var(--color-table-shade)",
        // Shadcn/ui compatible colors
        background: "var(--background)",
        foreground: "var(--foreground)",
        card: "var(--card)",
        "card-foreground": "var(--card-foreground)",
        popover: "var(--popover)",
        "popover-foreground": "var(--popover-foreground)",
        "primary-foreground": "var(--primary-foreground)",
        secondary: "var(--secondary)",
        "secondary-foreground": "var(--secondary-foreground)",
        muted: "var(--muted)",
        "muted-foreground": "var(--muted-foreground)",
        accent: "var(--accent)",
        "accent-foreground": "var(--accent-foreground)",
        destructive: "var(--destructive)",
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
      },
      fontFamily: {
        sans: ["var(--font-inter)", "sans-serif"],
        mono: ["var(--font-sometype)", "monospace"],
        inter: ["var(--font-inter)", "sans-serif"],
        sometype: ["var(--font-sometype)", "monospace"],
      },
      borderRadius: {
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
      },
      boxShadow: {
        glass: "var(--shadow-glass)",
      },
    },
  },
  plugins: [],
};
